name: 'Deploy AtScale POC'
description: 'Provisions an Azure VM, installs MicroK8s, and deploys AtScale with HTTPS Ingress.'
author: 'AtScale Engineering'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  client_id:
    description: 'Client Name (e.g. acme). Lowercase, no spaces.'
    required: true
  region:
    description: 'Azure Region'
    required: false
    default: 'eastus'
  azure_client_id:
    description: 'Azure Service Principal Client ID'
    required: true
  azure_tenant_id:
    description: 'Azure Tenant ID'
    required: true
  azure_subscription_id:
    description: 'Azure Subscription ID'
    required: true
  ssh_public_key:
    description: 'SSH Public Key for VM access'
    required: true
  ssh_private_key:
    description: 'SSH Private Key for remote execution'
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Provision Infrastructure
      id: infra
      uses: azure/cli@v1
      with:
        inlineScript: |
          RG="rg-poc-${{ inputs.client_id }}"
          VM="vm-atscale-${{ inputs.client_id }}"
          DNS="atscale-${{ inputs.client_id }}"
          
          echo "Creating Resource Group: $RG"
          az group create --name $RG --location ${{ inputs.region }} --tags Lifecycle=POC

          echo "Creating VM..."
          # Standard_DC2ds_v3 selected for Free Trial Quota compatibility
          az vm create \
            --resource-group $RG \
            --name $VM \
            --image Ubuntu2404 \
            --admin-username atscale \
            --ssh-key-values "${{ inputs.ssh_public_key }}" \
            --size Standard_DC2ds_v3 \
            --public-ip-sku Standard \
            --public-ip-address-dns-name $DNS \
            --tags Lifecycle=POC Schedule=BusinessHours \
            --os-disk-size-gb 256

          # Open Ports
          az vm open-port -g $RG -n $VM --port 22,80,443,16443,15432,11111 --priority 1010

          # Static IP Lock Logic (The "Hybrid" Fix)
          PRIVATE_IP=$(az vm show -d -g $RG -n $VM --query privateIps -o tsv)
          NIC_ID=$(az vm show -g $RG -n $VM --query "networkProfile.networkInterfaces[0].id" -o tsv)
          NIC_NAME=$(basename $NIC_ID)
          IP_CONFIG_NAME=$(az network nic show --ids $NIC_ID --query "ipConfigurations[0].name" -o tsv)
          
          if [ -z "$PRIVATE_IP" ] || [ -z "$IP_CONFIG_NAME" ]; then
            echo "Error: Missing IP or Config Name. Skipping static lock."
          else
            az network nic ip-config update \
              --resource-group $RG \
              --nic-name $NIC_NAME \
              --name $IP_CONFIG_NAME \
              --set privateIPAllocationMethod=Static \
              --private-ip-address $PRIVATE_IP
            echo "Private IP $PRIVATE_IP is now Static."
          fi

          # Outputs for next steps
          FQDN=$(az network public-ip list -g $RG --query "[0].dnsSettings.fqdn" -o tsv)
          IP=$(az vm show -d -g $RG -n $VM --query publicIps -o tsv)
          
          # Write to GITHUB_OUTPUT for composite usage
          echo "fqdn=$FQDN" >> $GITHUB_OUTPUT
          echo "public_ip=$IP" >> $GITHUB_OUTPUT

    - name: Wait for Boot
      shell: bash
      run: sleep 60

    - name: Configure Software
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.infra.outputs.public_ip }}
        username: atscale
        key: ${{ inputs.ssh_private_key }}
        timeout: 20m
        script: |
          # 0. Setup Path
          export PATH=$PATH:/snap/bin

          # 1. Install Tools
          sudo snap install microk8s --classic
          sudo snap install helm --classic
          sudo snap install kubectl --classic
          
          # 2. Fix Swap
          sudo swapoff -a
          sudo sed -i '/swap/d' /etc/fstab

          # 3. Setup MicroK8s & MetalLB
          PRIVATE_IP=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+')
          sudo microk8s status --wait-ready
          sudo microk8s enable hostpath-storage dns ingress
          sudo microk8s enable metallb:$PRIVATE_IP/32

          # 4. Generate Certs (Self-Contained)
          FQDN="${{ steps.infra.outputs.fqdn }}"
          echo "Generating certs for $FQDN"
          
          openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
            -keyout tls.key -out tls.crt \
            -subj "/C=US/ST=MA/L=Boston/O=AtScale/CN=$FQDN"
            
          # 5. Kube Config
          mkdir -p /home/atscale/.kube
          sudo microk8s config > /home/atscale/.kube/config
          sudo chown -R atscale:atscale /home/atscale/.kube
          chmod 600 /home/atscale/.kube/config
          
          # Create Secret
          kubectl create secret tls atscale-tls-secret --cert=tls.crt --key=tls.key -n atscale --dry-run=client -o yaml | kubectl apply -f -

          # 6. Generate Default Values File
          # (You can edit this block to match your standard production values)
          cat <<EOF > values.yaml
          global:
            atscale:
              externalHostname: $FQDN
          EOF

          # 7. Deploy AtScale
          helm upgrade --install atscale oci://registry-1.docker.io/atscaleinc/atscale \
            --version 2025.10.0 \
            -n atscale --create-namespace \
            --kubeconfig /home/atscale/.kube/config \
            --values ./values.yaml \
            --wait --timeout 15m

          # 8. Configure Ingress (The Fix)
          cat <<EOF > ingress.yaml
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: atscale-ui-ingress
            namespace: atscale
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_set_header Host \$host;
          spec:
            ingressClassName: public
            tls:
            - hosts:
              - $FQDN
              secretName: atscale-tls-secret
            rules:
            - host: $FQDN
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: atscale-ingress-gateway 
                      port:
                        number: 443
          EOF
          
          sudo microk8s kubectl apply -f ingress.yaml

          # 9. Print Credentials
          echo "=============================================="
          AS_USER=$(sudo microk8s kubectl get secret --namespace atscale atscale-kc-users -o jsonpath="{.data.atscaleAdmin}" | base64 -d)
          AS_PASS=$(sudo microk8s kubectl get secret --namespace atscale atscale-kc-users -o jsonpath="{.data.atscaleAdminPassword}" | base64 -d)
          echo "AtScale URL: https://$FQDN"
          echo "Username: $AS_USER"
          echo "Password: $AS_PASS"
          echo "=============================================="
